name: FacilitiesDesignGroupPC
favicon: null
layout_spectrum: 0.016967458417639136
typography_spectrum: 0.8446060556452721
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.2236556785646826
  lightness: 0.6071009535808116
  saturation: 0.8253897640388459
  rhythmicContrast: 0.7398957684636116
purpose: []
